const mongoose = require('mongoose');

/**
 * GIVEN BY USER :
 * -job description - string
 * - resume text - string
 * -self description - string
 * 
 * GENERATED BY GEMINI API:
 * 
 * -match score : Number
 * 
 * -technical questions : (stored in array of objects)
 * [{
 *   question: String,
 *   intention: String,
 *   answer: String
 * }] 
 * 
 * 
 * 
 * 
 * -behaviral questions : (stored in array of objects)
 * [{
 *   question: String,
 *   intention: String,
 *   answer: String
 * }]
 * 
 *  
 * -skill gaps : (stored in array of objects)
 * [{
 *  skill: String,
 *  severity :{
 *   type: String,
 *   enum: ['low', 'medium', 'high'],
 *   }
 * }]
 * -preparation plan :  (stored in array of objects)
 * [{
 *   day:Number,
 *   focus : String
 *   task : array of string
 * }]
 * 
 * 
 */

//Subschema :-
const technicalQuestionSchema = new mongoose.Schema({
    question:{
        type: String,
        required: [true, "Technical question is required"]
    },

    intention :{
        type:String ,
        required : [true , "Intention is required"]

    },

    answer: {
        type : String,
        required:[true , "Answer is required"]
    }


},
{
    _id: false
 }) 
    //Mongoose automatically creates an _id for every document and every subdocument.
    // technicalQuestionSchema is  going to be used as a subdocument inside interviewReportSchema document and we dont need 
    // to uniquely identify(fro _id) each individual question, those _ids are unnecessary.
    // but The parent document has _id, while each embedded technical-question object doesn't.
    // e.g {
//     _id: ObjectId("parent123"),
//     technicalQuestions: [
//         {
//             question: "...",
//             intention: "...",
//             answer: "..."
//         },
 //{
//             question: "...",
//             intention: "...",
//             answer: "..."
//         }
//     ]
// }



// SubSchema :

const behavioralQuestionSchema = new mongoose.Schema({
     question:{
        type: String,
        required: [true, "behavioral question is required"]
    },

    intention :{
        type:String ,
        required : [true , "Intention is required"]

    },

    answer: {
        type : String,
        required:[true , "Answer is required"]
    }


},
{
    _id: false 

})

// question , intention , answer these are field names , so they can be same or diff in diff schema


// SubSchema

const skillGapSchema = new mongoose.Schema({
    skill: {
        type: String,
        required: [true , "Skill is required"]
    },

    severity:{
        type: String,
        enum: [ "low" , "medium", "high"],
        required: [true , "Severity is required"]
    },
    

}, 
 {
        _id: false
})

// SubSchema :
const preparationPlanSchema = new mongoose.Schema({
    day:{
        type: String,
        required:[true , "Day is required" ]

    }, 

    focus:{
        type: String,
        required: [true , "Focus is required"]
    },

    task: [ // array
        {
            type:String,
            required: [true , "Task is required"]
        }
    ]


})


// Schema:-
const interviewReportSchema = new mongoose.Schema({
    jobDescription: {
        type: String,
        required: [true , "Job description is required"]
    },

    resume : {
        type: String,
    },

    selfDescription: {
        type: String
    },

    matchScore: {
        type: Number,
        min: 0,
        max: 100
    },

    technicalQuestion: [technicalQuestionSchema],
    behavioralQuestion: [behavioralQuestionSchema],
    skillGaps: [skillGapSchema],
    preparationPlana:[preparationPlanSchema]
    // The square brackets [] mean: these fields will be array ( subdocuments will be element of array)
},
{
    timestamps: true
})

const interviewReportModel = mongoose.model("InterviewReport" , interviewReportSchema);
module.exports = interviewReportModel;